In [1]:
import pandas as pd
import geopandas as geo
from shapely.geometry import Point
import math

In [2]:
df_clc = pd.read_csv("points_rtr.csv", sep=",",index_col=0)

In [3]:
AUT_map_Merged = pd.read_csv("Merged_data_ALL.csv",index_col=0)

In [4]:

AUT_map_Merged = AUT_map_Merged.assign(AverageDOWNLOAD = 0)
AUT_map_Merged = AUT_map_Merged.assign(AverageUPLOAD = 0)
AUT_map_Merged = AUT_map_Merged.assign(Averageping_ms = 0)
AUT_map_Merged = AUT_map_Merged.assign(Averagelte_rsrp = 0)
AUT_map_Merged = AUT_map_Merged.assign(Averagelte_rsrq = 0)
AUT_map_Merged = AUT_map_Merged.assign(Averagendt_download_kbit = 0)
AUT_map_Merged = AUT_map_Merged.assign(Averagendt_upload_kbit = 0)
AUT_map_Merged = AUT_map_Merged.assign(Averagesignal_strength = 0)
AUT_map_Merged = AUT_map_Merged.assign(Averagedtm_level = 0)


df_clc.head(50)
AUT_map_Merged.head(50)

,id,left,top,right,bottom,geometry,IndexListe,AverageDOWNLOAD,AverageUPLOAD,Averageping_ms,Averagelte_rsrp,Averagelte_rsrq,Averagendt_download_kbit,Averagendt_upload_kbit,Averagesignal_strength,Averagedtm_level
0,188,112750.0,327431.8348,113750.0,326431.8348,"POLYGON ((112749.9999999999 383000.0000014922,...",[],0,0,0,0,0,0,0,0,0
1,189,112750.0,326431.8348,113750.0,325431.8348,"POLYGON ((112750 382000.0000014934, 113750 382...","[1280514, 2586013, 1500837, 550053, 9125, 1027...",0,0,0,0,0,0,0,0,0
2,190,112750.0,325431.8348,113750.0,324431.8348,"POLYGON ((112749.9999999999 381000.0000014932,...",[],0,0,0,0,0,0,0,0,0
3,477,113750.0,329431.8348,114750.0,328431.8348,"POLYGON ((113749.9999999999 385000.0000014925,...",[1125],0,0,0,0,0,0,0,0,0
4,478,113750.0,328431.8348,114750.0,327431.8348,"POLYGON ((113750.0000000001 384000.0000014937,...",[],0,0,0,0,0,0,0,0,0
5,479,113750.0,327431.8348,114750.0,326431.8348,"POLYGON ((113750.0000000001 383000.0000014936,...",[],0,0,0,0,0,0,0,0,0
6,480,113750.0,326431.8348,114750.0,325431.8348,"POLYGON ((113750 382000.0000014941, 114750.000...",[],0,0,0,0,0,0,0,0,0
7,481,113750.0,325431.8348,114750.0,324431.8348,"POLYGON ((113750 381000.0000014932, 114749.999...","[799363, 2565572, 1742215, 775306, 2002572, 43...",0,0,0,0,0,0,0,0,0
8,482,113750.0,324431.8348,114750.0,323431.8348,"POLYGON ((113750.0000000001 380000.0000014944,...",[],0,0,0,0,0,0,0,0,0
9,483,113750.0,323431.8348,114750.0,322431.8348,"POLYGON ((113750.0000000001 379000.0000014942,...",[],0,0,0,0,0,0,0,0,0
10,484,113750.0,322431.8348,114750.0,321431.8348,"POLYGON ((113749.9999999999 378000.0000014912,...","[1350121, 1364426, 1350111, 3034830, 3034831, ...",0,0,0,0,0,0,0,0,0
11,485,113750.0,321431.8348,114750.0,320431.8348,"POLYGON ((113749.9999999999 377000.0000014924,...","[1436289, 1620996, 443398, 443402, 409106, 143...",0,0,0,0,0,0,0,0,0
12,486,113750.0,320431.8348,114750.0,319431.8348,"POLYGON ((113750.0000000001 376000.0000014937,...",[],0,0,0,0,0,0,0,0,0
13,491,113750.0,315431.8348,114750.0,314431.8348,"POLYGON ((113750 371000.0000014927, 114749.999...",[],0,0,0,0,0,0,0,0,0
14,767,114750.0,330431.8348,115750.0,329431.8348,"POLYGON ((114750 386000.0000014927, 115750.000...",[],0,0,0,0,0,0,0,0,0
15,768,114750.0,329431.8348,115750.0,328431.8348,"POLYGON ((114750.0000000001 385000.0000014947,...",[],0,0,0,0,0,0,0,0,0
16,769,114750.0,328431.8348,115750.0,327431.8348,"POLYGON ((114750 384000.0000014937, 115749.999...",[],0,0,0,0,0,0,0,0,0
17,770,114750.0,327431.8348,115750.0,326431.8348,"POLYGON ((114750.0000000001 383000.0000014936,...",[],0,0,0,0,0,0,0,0,0
18,771,114750.0,326431.8348,115750.0,325431.8348,"POLYGON ((114750.0000000001 382000.0000014941,...",[],0,0,0,0,0,0,0,0,0
19,772,114750.0,325431.8348,115750.0,324431.8348,"POLYGON ((114749.9999999999 381000.0000014925,...","[600064, 600065, 1056258, 454146, 1579018, 600...",0,0,0,0,0,0,0,0,0
20,773,114750.0,324431.8348,115750.0,323431.8348,"POLYGON ((114749.9999999999 380000.0000014916,...","[3143682, 1592835, 683012, 1221127, 2073095, 1...",0,0,0,0,0,0,0,0,0
21,774,114750.0,323431.8348,115750.0,322431.8348,"POLYGON ((114749.9999999999 379000.0000014935,...","[3122560, 1519494, 3108103, 3122447, 3028624, ...",0,0,0,0,0,0,0,0,0
22,775,114750.0,322431.8348,115750.0,321431.8348,"POLYGON ((114750.0000000001 378000.0000014933,...","[2791426, 2201604, 2523146, 2201626, 1640485, ...",0,0,0,0,0,0,0,0,0
23,776,114750.0,321431.8348,115750.0,320431.8348,"POLYGON ((114749.9999999999 377000.0000014945,...","[672259, 713732, 1734152, 3418125, 1734158, 16...",0,0,0,0,0,0,0,0,0
24,777,114750.0,320431.8348,115750.0,319431.8348,"POLYGON ((114750.0000000001 376000.0000014944,...","[1603203, 9732, 1855374, 2942863, 2239638, 824...",0,0,0,0,0,0,0,0,0
25,778,114750.0,319431.8348,115750.0,318431.8348,"POLYGON ((114750.0000000001 375000.0000014942,...",[],0,0,0,0,0,0,0,0,0
26,779,114750.0,318431.8348,115750.0,317431.8348,"POLYGON ((114749.9999999999 374000.000001494, ...",[],0,0,0,0,0,0,0,0,0
27,780,114750.0,317431.8348,115750.0,316431.8348,"POLYGON ((114749.9999999999 373000.0000014931,...",[],0,0,0,0,0,0,0,0,0
28,781,114750.0,316431.8348,115750.0,315431.8348,"POLYGON ((114750.0000000001 372000.0000014943,...",[],0,0,0,0,0,0,0,0,0
29,782,114750.0,315431.8348,115750.0,314431.8348,"POLYGON ((114749.9999999999 371000.0000014934,...",[],0,0,0,0,0,0,0,0,0
30,1036,115750.0,352431.8348,116750.0,351431.8348,"POLYGON ((115749.9999999999 408000.0000014926,...",[],0,0,0,0,0,0,0,0,0
31,1037,115750.0,351431.8348,116750.0,350431.8348,"POLYGON ((115749.9999999999 407000.0000014931,...",[],0,0,0,0,0,0,0,0,0
32,1038,115750.0,350431.8348,116750.0,349431.8348,"POLYGON ((115750 406000.0000014944, 116750 406...",[],0,0,0,0,0,0,0,0,0
33,1057,115750.0,331431.8348,116750.0,330431.8348,"POLYGON ((115750 387000.0000014943, 116750 387...",[],0,0,0,0,0,0,0,0,0
34,1058,115750.0,330431.8348,116750.0,329431.8348,"POLYGON ((115750.0000000001 386000.0000014934,...","[587147, 9742, 3029647, 3029648, 3029649, 3029...",0,0,0,0,0,0,0,0,0
35,1059,115750.0,329431.8348,116750.0,328431.8348,"POLYGON ((115750 385000.000001494, 116749.9999...","[944145, 2103321, 1695773, 1024031, 1155108, 6...",0,0,0,0,0,0,0,0,0
36,1060,115750.0,328431.8348,116750.0,327431.8348,"POLYGON ((115749.9999999999 384000.0000014937,...","[827392, 1638401, 2299908, 1556491, 1609741, 2...",0,0,0,0,0,0,0,0,0
37,1061,115750.0,327431.8348,116750.0,326431.8348,"POLYGON ((115749.9999999999 383000.0000014915,...",[],0,0,0,0,0,0,0,0,0
38,1062,115750.0,326431.8348,116750.0,325431.8348,"POLYGON ((115750 382000.0000014948, 116750 382...",[3125258],0,0,0,0,0,0,0,0,0
39,1063,115750.0,325431.8348,116750.0,324431.8348,"POLYGON ((115750.0000000001 381000.0000014939,...","[3368742, 3266440, 2453513, 2142856, 3368781, ...",0,0,0,0,0,0,0,0,0
40,1064,115750.0,324431.8348,116750.0,323431.8348,"POLYGON ((115749.9999999999 380000.0000014923,...","[2086916, 3035142, 3035143, 3035145, 3035147, ...",0,0,0,0,0,0,0,0,0
41,1065,115750.0,323431.8348,116750.0,322431.8348,"POLYGON ((115750 379000.0000014935, 116750.000...","[3035136, 1218561, 1222146, 3035137, 1203204, ...",0,0,0,0,0,0,0,0,0
42,1066,115750.0,322431.8348,116750.0,321431.8348,"POLYGON ((115750 378000.0000014933, 116749.999...","[2043918, 2756630, 2639894, 1511453, 2469919, ...",0,0,0,0,0,0,0,0,0
43,1067,115750.0,321431.8348,116750.0,320431.8348,"POLYGON ((115750.0000000001 377000.0000014945,...","[3096065, 140805, 2358790, 3096071, 805900, 27...",0,0,0,0,0,0,0,0,0
44,1068,115750.0,320431.8348,116750.0,319431.8348,"POLYGON ((115750 376000.0000014944, 116750 376...","[2226176, 2734593, 1375234, 526851, 997893, 34...",0,0,0,0,0,0,0,0,0
45,1069,115750.0,319431.8348,116750.0,318431.8348,"POLYGON ((115749.9999999998 375000.0000014927,...",[],0,0,0,0,0,0,0,0,0
46,1070,115750.0,318431.8348,116750.0,317431.8348,"POLYGON ((115750 374000.000001494, 116750 3740...",[],0,0,0,0,0,0,0,0,0
47,1071,115750.0,317431.8348,116750.0,316431.8348,"POLYGON ((115749.9999999999 373000.0000014938,...",[],0,0,0,0,0,0,0,0,0
48,1072,115750.0,316431.8348,116750.0,315431.8348,"POLYGON ((115749.9999999999 372000.0000014922,...",[],0,0,0,0,0,0,0,0,0
49,1073,115750.0,315431.8348,116750.0,314431.8348,"POLYGON ((115750 371000.0000014927, 116750 371...",[],0,0,0,0,0,0,0,0,0

In [7]:
df_clc.columns

Index(['network_type', 'download_kbit', 'upload_kbit', 'ping_ms', 'lte_rsrp',
       'lte_rsrq', 'platform', 'model', 'network_name', 'ndt_download_kbit',
       'ndt_upload_kbit', 'signal_strength', 'pinned', 'dtm_level',
       'signal_classification', 'geometry'],
      dtype='object')

In [8]:
math.isnan(df_clc["network_name"][0])

True

In [5]:
for i in range(0,len(AUT_map_Merged)):
    summe1 = 0 
    summe2 = 0
    summe3 = 0
    summe4 = 0
    summe5 = 0
    summe6 = 0
    summe7 = 0
    summe8 = 0
    summe9  = 0
    
    count1 = 0
    count2 = 0
    count3 = 0
    count4 = 0
    count5 = 0
    count6 = 0
    count7 = 0
    count8 = 0
    count9 = 0
    
    liste = AUT_map_Merged["IndexListe"][i].strip('][').split(', ')
    for j in liste:
        if j != "":
            if math.isnan(df_clc.loc[int(j),"download_kbit"]) == False:
                summe1  = summe1 + df_clc.loc[int(j),"download_kbit"]
                count1 = count1 + 1
            if math.isnan(df_clc.loc[int(j),"upload_kbit"]) == False:
                summe2  = summe2 + df_clc.loc[int(j),"upload_kbit"]
                count2 = count2 + 1         
            if math.isnan(df_clc.loc[int(j),"ping_ms"]) == False:
                summe3  = summe3 + df_clc.loc[int(j),"ping_ms"]
                count3 = count3 + 1
            if math.isnan(df_clc.loc[int(j),"lte_rsrp"]) == False:
                summe4  = summe4 + df_clc.loc[int(j),"lte_rsrp"]
                count4 = count4 + 1
            if math.isnan(df_clc.loc[int(j),"lte_rsrq"]) == False:
                summe5  = summe5 + df_clc.loc[int(j),"lte_rsrq"]
                count5 = count5 + 1
            if math.isnan(df_clc.loc[int(j),"ndt_download_kbit"]) == False:
                summe6  = summe6 + df_clc.loc[int(j),"ndt_download_kbit"]
                count6 = count6 + 1
            if math.isnan(df_clc.loc[int(j),"ndt_upload_kbit"]) == False:
                summe7  = summe7 + df_clc.loc[int(j),"ndt_upload_kbit"]
                count7 = count7 + 1
            if math.isnan(df_clc.loc[int(j),"signal_strength"]) == False:
                summe8  = summe8 + df_clc.loc[int(j),"signal_strength"]
                count8 = count8 + 1
            if math.isnan(df_clc.loc[int(j),"dtm_level"]) == False:
                summe9  = summe9 + df_clc.loc[int(j),"dtm_level"]
                count9 = count9 + 1

            
    if count1 == 0:
         AUT_map_Merged.loc[i, "AverageDOWNLOAD"] = float('nan')
    else:      
        AUT_map_Merged.loc[i, "AverageDOWNLOAD"] = summe1/max(count1,1) 
        
    if count2 == 0:
        AUT_map_Merged.loc[i, "AverageUPLOAD"] = float('nan')
    else:  
        AUT_map_Merged.loc[i, "AverageUPLOAD"] = summe2/max(count2,1)
        
    if count3 == 0:
        AUT_map_Merged.loc[i, "Averageping_ms"] = float('nan')
    else:
        AUT_map_Merged.loc[i, "Averageping_ms"] = summe3/max(count3,1)
        
    if count4 == 0:
        AUT_map_Merged.loc[i, "Averagelte_rsrp"] = float('nan')
    else:
        AUT_map_Merged.loc[i, "Averagelte_rsrp"] = summe4/max(count4,1)
        
    if count5 == 0:
        AUT_map_Merged.loc[i, "Averagelte_rsrq"] = float('nan') 
    else:
        AUT_map_Merged.loc[i, "Averagelte_rsrq"] = summe5/max(count5,1) 
        
    if count6 == 0:
        AUT_map_Merged.loc[i, "Averagendt_download_kbit"] = float('nan')  
    else:
         AUT_map_Merged.loc[i, "Averagendt_download_kbit"] = summe6/max(count6,1) 
            
    if count7 == 0:
        AUT_map_Merged.loc[i, "Averagendt_upload_kbit"] = float('nan') 
    else:
        AUT_map_Merged.loc[i, "Averagendt_upload_kbit"] = summe7/max(count7,1)
        
    if count8 == 0:
        AUT_map_Merged.loc[i, "Averagesignal_strength"] = float('nan') 
    else:
        AUT_map_Merged.loc[i, "Averagesignal_strength"] = summe8/max(count8,1)

    if count9 == 0:
        AUT_map_Merged.loc[i, "Averagedtm_level"] = float('nan') 
    else:
         AUT_map_Merged.loc[i, "Averagedtm_level"] = summe9/max(count9,1)
    

        #df_clc["IndexListe"][j]

In [46]:
AUT_map_Merged.head(50)

,id,left,top,right,bottom,geometry,IndexListe,AverageDOWNLOAD,AverageUPLOAD,Averageping_ms,Averagelte_rsrp,Averagelte_rsrq,Averagendt_download_kbit,Averagendt_upload_kbit,Averagesignal_strength,Averagedtm_level
0,188,112750.0,327431.8348,113750.0,326431.8348,"POLYGON ((112749.9999999999 383000.0000014922,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,189,112750.0,326431.8348,113750.0,325431.8348,"POLYGON ((112750 382000.0000014934, 113750 382...","[3001184, 550053, 9125, 994799, 3001181, 2586013]",35965.166667,5851.000000,31.616667,-106.000000,-12.000000,NaN,NaN,-55.000000,386.000000
2,190,112750.0,325431.8348,113750.0,324431.8348,"POLYGON ((112749.9999999999 381000.0000014932,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,477,113750.0,329431.8348,114750.0,328431.8348,"POLYGON ((113749.9999999999 385000.0000014925,...",[1125],12764.000000,6767.000000,23.200000,NaN,NaN,NaN,NaN,-45.000000,NaN
4,478,113750.0,328431.8348,114750.0,327431.8348,"POLYGON ((113750.0000000001 384000.0000014937,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,479,113750.0,327431.8348,114750.0,326431.8348,"POLYGON ((113750.0000000001 383000.0000014936,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,480,113750.0,326431.8348,114750.0,325431.8348,"POLYGON ((113750 382000.0000014941, 114750.000...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,481,113750.0,325431.8348,114750.0,324431.8348,"POLYGON ((113750 381000.0000014932, 114749.999...","[799363, 2565573, 775306, 2002572, 438545, 534...",29079.034483,9221.603448,37.513793,-94.333333,-12.333333,129101.000000,18913.000000,-50.666667,435.020833
8,482,113750.0,324431.8348,114750.0,323431.8348,"POLYGON ((113750.0000000001 380000.0000014944,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,483,113750.0,323431.8348,114750.0,322431.8348,"POLYGON ((113750.0000000001 379000.0000014942,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,484,113750.0,322431.8348,114750.0,321431.8348,"POLYGON ((113749.9999999999 378000.0000014912,...","[3083935, 3034830, 3034831]",50285.000000,17417.666667,27.066667,-104.500000,-13.000000,41002.000000,4760.000000,-64.000000,NaN
11,485,113750.0,321431.8348,114750.0,320431.8348,"POLYGON ((113749.9999999999 377000.0000014924,...","[443398, 443402, 409106, 409125, 408513, 32339...",61123.650000,14107.900000,37.595000,-96.000000,-11.500000,1868.000000,643.000000,-57.555556,476.666667
12,486,113750.0,320431.8348,114750.0,319431.8348,"POLYGON ((113750.0000000001 376000.0000014937,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,491,113750.0,315431.8348,114750.0,314431.8348,"POLYGON ((113750 371000.0000014927, 114749.999...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,767,114750.0,330431.8348,115750.0,329431.8348,"POLYGON ((114750 386000.0000014927, 115750.000...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,768,114750.0,329431.8348,115750.0,328431.8348,"POLYGON ((114750.0000000001 385000.0000014947,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,769,114750.0,328431.8348,115750.0,327431.8348,"POLYGON ((114750 384000.0000014937, 115749.999...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,770,114750.0,327431.8348,115750.0,326431.8348,"POLYGON ((114750.0000000001 383000.0000014936,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,771,114750.0,326431.8348,115750.0,325431.8348,"POLYGON ((114750.0000000001 382000.0000014941,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,772,114750.0,325431.8348,115750.0,324431.8348,"POLYGON ((114749.9999999999 381000.0000014925,...","[600064, 600065, 454146, 600077, 2726925, 6000...",38127.179487,8366.367521,34.682906,-107.200000,-11.360000,NaN,NaN,-53.657143,436.486726
20,773,114750.0,324431.8348,115750.0,323431.8348,"POLYGON ((114749.9999999999 380000.0000014916,...","[3143682, 683012, 2073095, 2800142, 972308, 21...",29984.518349,9659.431193,40.669266,-111.250000,-13.214286,14728.666667,4264.333333,-60.753425,438.023529
21,774,114750.0,323431.8348,115750.0,322431.8348,"POLYGON ((114749.9999999999 379000.0000014935,...","[3122560, 3108103, 3122447, 3028624, 3028753, ...",27370.375000,9565.410714,35.842857,-107.452381,-15.452381,NaN,NaN,-52.000000,566.250000
22,775,114750.0,322431.8348,115750.0,321431.8348,"POLYGON ((114750.0000000001 378000.0000014933,...","[2791426, 2201604, 2523146, 2201626, 3323945, ...",41397.618462,13674.538462,29.463077,-95.196581,-11.940171,15045.750000,3978.625000,-53.521472,445.938406
23,776,114750.0,321431.8348,115750.0,320431.8348,"POLYGON ((114749.9999999999 377000.0000014945,...","[672259, 713732, 3418125, 3424020, 3014167, 34...",23630.882353,9158.823529,38.123529,-96.785714,-13.571429,NaN,NaN,-72.571429,463.615385
24,777,114750.0,320431.8348,115750.0,319431.8348,"POLYGON ((114750.0000000001 376000.0000014944,...","[9732, 2942863, 2239638, 824343, 434456, 24053...",63940.921053,12866.815789,35.134211,-105.000000,-14.000000,NaN,NaN,-49.500000,465.848485
25,778,114750.0,319431.8348,115750.0,318431.8348,"POLYGON ((114750.0000000001 375000.0000014942,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,779,114750.0,318431.8348,115750.0,317431.8348,"POLYGON ((114749.9999999999 374000.000001494, ...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,780,114750.0,317431.8348,115750.0,316431.8348,"POLYGON ((114749.9999999999 373000.0000014931,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,781,114750.0,316431.8348,115750.0,315431.8348,"POLYGON ((114750.0000000001 372000.0000014943,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,782,114750.0,315431.8348,115750.0,314431.8348,"POLYGON ((114749.9999999999 371000.0000014934,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1036,115750.0,352431.8348,116750.0,351431.8348,"POLYGON ((115749.9999999999 408000.0000014926,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1037,115750.0,351431.8348,116750.0,350431.8348,"POLYGON ((115749.9999999999 407000.0000014931,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,1038,115750.0,350431.8348,116750.0,349431.8348,"POLYGON ((115750 406000.0000014944, 116750 406...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,1057,115750.0,331431.8348,116750.0,330431.8348,"POLYGON ((115750 387000.0000014943, 116750 387...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1058,115750.0,330431.8348,116750.0,329431.8348,"POLYGON ((115750.0000000001 386000.0000014934,...","[587147, 9742, 3029647, 3029648, 3029649, 3029...",32192.133333,15302.866667,35.866667,-104.625000,-13.437500,NaN,NaN,-91.000000,422.800000
35,1059,115750.0,329431.8348,116750.0,328431.8348,"POLYGON ((115750 385000.000001494, 116749.9999...","[2952192, 394245, 2141701, 944145, 3423253, 20...",30344.069519,10298.636364,32.654545,-101.703704,-11.692308,NaN,NaN,-70.400000,424.801587
36,1060,115750.0,328431.8348,116750.0,327431.8348,"POLYGON ((115749.9999999999 384000.0000014937,...","[827392, 2299908, 2975757, 624658, 2670619, 27...",18254.008000,6536.194000,49.381200,-106.875000,-12.375000,NaN,NaN,-50.293065,427.046414
37,1061,115750.0,327431.8348,116750.0,326431.8348,"POLYGON ((115749.9999999999 383000.0000014915,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,1062,115750.0,326431.8348,116750.0,325431.8348,"POLYGON ((115750 382000.0000014948, 116750 382...",[3125258],16235.000000,1357.000000,61.000000,NaN,NaN,NaN,NaN,NaN,NaN
39,1063,115750.0,325431.8348,116750.0,324431.8348,"POLYGON ((115750.0000000001 381000.0000014939,...","[3368742, 3266440, 2142856, 2453513, 3368781, ...",13094.333333,4043.500000,38.783333,-107.333333,-16.000000,NaN,NaN,-68.000000,441.666667
40,1064,115750.0,324431.8348,116750.0,323431.8348,"POLYGON ((115749.9999999999 380000.0000014923,...","[2086916, 3035142, 3035143, 3035145, 3035147, ...",45437.343042,16385.058252,35.525566,-101.965035,-12.489510,NaN,NaN,-59.515464,454.013986
41,1065,115750.0,323431.8348,116750.0,322431.8348,"POLYGON ((115750 379000.0000014935, 116750.000...","[3035136, 3035137, 3035138, 3035140, 3035141, ...",42919.104348,13567.591304,62.668261,-98.126761,-12.112676,NaN,NaN,-50.225000,449.406667
42,1066,115750.0,322431.8348,116750.0,321431.8348,"POLYGON ((115750 378000.0000014933, 116749.999...","[955904, 2957825, 3244545, 3233283, 3447811, 2...",38863.234513,10357.292035,34.551327,-99.200000,-12.700000,NaN,NaN,-60.452632,465.945055
43,1067,115750.0,321431.8348,116750.0,320431.8348,"POLYGON ((115750.0000000001 377000.0000014945,...","[3096065, 140805, 2358790, 3096071, 805900, 27...",31564.504202,10862.378151,48.830252,-94.869565,-12.608696,NaN,NaN,-64.291667,482.924051
44,1068,115750.0,320431.8348,116750.0,319431.8348,"POLYGON ((115750 376000.0000014944, 116750 376...","[2226176, 2734593, 526851, 997893, 3447813, 27...",48304.991453,7732.905983,24.578632,NaN,NaN,NaN,NaN,-55.755102,521.067416
45,1069,115750.0,319431.8348,116750.0,318431.8348,"POLYGON ((115749.9999999998 375000.0000014927,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,1070,115750.0,318431.8348,116750.0,317431.8348,"POLYGON ((115750 374000.000001494, 116750 3740...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,1071,115750.0,317431.8348,116750.0,316431.8348,"POLYGON ((115749.9999999999 373000.0000014938,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,1072,115750.0,316431.8348,116750.0,315431.8348,"POLYGON ((115749.9999999999 372000.0000014922,...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,1073,115750.0,315431.8348,116750.0,314431.8348,"POLYGON ((115750 371000.0000014927, 116750 371...",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
a = float('nan')
print(type(AUT_map_Merged.loc[0,"AverageDOWNLOAD"] == float('nan')))
j=0
k = len(AUT_map_Merged)
b = 80000
for i in AUT_map_Merged["AverageDOWNLOAD"][1:b]:

    if i > 0:
        j=j+1
print(j)    

k = len(AUT_map_Merged)
print(k)
print(j/b)
print(j/k)

<class 'numpy.bool_'>
33811
85409
0.4226375
0.39587162945357046

In [7]:
AUT_map_Merged.to_csv("MergedWithFigures_Merged_ALL.csv")

In [48]:
j1 = 0
j2 = 0
j3 = 0
j4 = 0
j5 = 0
j6 = 0
j7 = 0


for i in range(0,len(AUT_map_Merged)):
        
    if (AUT_map_Merged["AverageDOWNLOAD"][i]) < 15000 and (AUT_map_Merged["AverageDOWNLOAD"][i]) > 5000:
        #print(AUT_map_Merged["AverageDOWNLOAD"][i])
        j1 = j1 +1
    if (AUT_map_Merged["AverageDOWNLOAD"][i]) < 20000 and (AUT_map_Merged["AverageDOWNLOAD"][i]) > 10000:
        #print(AUT_map_Merged["AverageDOWNLOAD"][i])
        j2 = j2 +1
    if (AUT_map_Merged["AverageDOWNLOAD"][i]) < 25000 and (AUT_map_Merged["AverageDOWNLOAD"][i]) > 15000:
        #print(AUT_map_Merged["AverageDOWNLOAD"][i])
        j3 = j3 +1        
    if (AUT_map_Merged["AverageDOWNLOAD"][i]) < 30000 and (AUT_map_Merged["AverageDOWNLOAD"][i]) > 20000:
        #print(AUT_map_Merged["AverageDOWNLOAD"][i])
        j4 = j4 +1        
    if (AUT_map_Merged["AverageDOWNLOAD"][i]) < 35000 and (AUT_map_Merged["AverageDOWNLOAD"][i]) > 25000:
        #print(AUT_map_Merged["AverageDOWNLOAD"][i])
        j5 = j5 +1 
    if (AUT_map_Merged["AverageDOWNLOAD"][i]) < 60000 and (AUT_map_Merged["AverageDOWNLOAD"][i]) > 50000:
        #print(AUT_map_Merged["AverageDOWNLOAD"][i])
        j6 = j6 +1     
    if (AUT_map_Merged["AverageDOWNLOAD"][i]) < 100000 and (AUT_map_Merged["AverageDOWNLOAD"][i]) > 70000:
        #print(AUT_map_Merged["AverageDOWNLOAD"][i])
        j7 = j7 +1         
print(j1,j2,j3,j4,j5,j6,j7,'hallo')

6770 7863 8270 7766 6659 1769 1258 hallo